new_project:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: database
      schema: main
      schemas_and_paths:
        main: C:/Python/Proyecto/new_project.sqlite
      schema_directory: C:/Python/Proyecto
