name: 'new_project'
version: '1.0'
config-version: 2
profile: 'new_project'

model-paths: ['models']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
analysis-paths: ['analyses']
test-paths: ['tests']

target-path: 'target'
clean-targets: ['target','dbt_packages']

models:
  new_project:
    +materialized: table